services:
  wordpress:
    image: wordpress:php8.3-apache
    ports:
      - "8888:80"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    command: >
      bash -c "chown www-data:www-data /var/www/html/wp-content && apache2-foreground"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8888');
        define('WP_SITEURL', 'http://localhost:8888');
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordmove:
    image: welaika/wordmove
    volumes:
      - ./Movefile.yml:/html/Movefile.yml
      - ./.env:/html/.env
      - ./wordpress/wp-content:/html/wp-content
      - ${SSH_KEY_PATH}:/root/.ssh/id_rsa:ro
    depends_on:
      - db

volumes:
  db_data:
